name: Push

on:
  repository_dispatch:
    types: [pull_deb]

jobs:
  pull_package:
    runs-on: ubuntu-22.04
    env:
      SUPPORTED_VERSIONS: |
        jammy
        lunar
    steps:
      - name: Pull package
        shell: bash
        id: pull_package
        run: |+
          echo ${SUPPORTED_VERSIONS[*]}
          if ! [[ ${SUPPORTED_VERSIONS[*]} =~ "${{ github.event.client_payload.version }}" ]] ; then
            exit 1
          fi

          RESPONSE=$(curl -sfL -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/telekom-mms/${{ github.event.client_payload.repo }}/releases/tags/${{ github.event.client_payload.tag }}")
          readarray -t files < <(echo $RESPONSE | jq -rc '.assets[].browser_download_url | select(test("\\.deb$"))')

          if [[ ${#files[@]} == 0 ]]; then
            exit 1
          fi

          for file in ${files[@]}
          do
            curl -sLO $file
            echo "result=true" >> $GITHUB_OUTPUT
          done
      - name: deploy releases
        if: steps.pull_package.outputs.result == 'true'
        uses: smeinecke/apt-repo-action@v2.1.4
        with:
          file: "*.deb"
          file_target_version: ${{ github.event.client_payload.version }}
          github_token: $GITHUB_TOKEN
          repo_supported_arch: |
            amd64
          repo_supported_version: ${{ env.SUPPORTED_VERSIONS }}
          public_key: ${{ secrets.PUB_KEY }}
          private_key: ${{ secrets.PRV_KEY }}
          key_passphrase: ""
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
